FROM python:3.12-slim

ARG DEBIAN_MIRROR=http://deb.debian.org/debian
ARG DEBIAN_SECURITY_MIRROR=http://deb.debian.org/debian-security
ARG PIP_INDEX_URL=https://pypi.org/simple

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    MPLBACKEND=Agg \
    MPLCONFIGDIR=/tmp/matplotlib

RUN sed -i \
      -e "s|http://deb.debian.org/debian-security|${DEBIAN_SECURITY_MIRROR}|g" \
      -e "s|http://deb.debian.org/debian|${DEBIAN_MIRROR}|g" \
      /etc/apt/sources.list.d/debian.sources \
    && apt-get update && apt-get install -y --no-install-recommends \
    r-base \
    r-cran-ggplot2 \
    r-cran-jsonlite \
    r-cran-readxl \
    r-cran-svglite \
    libcairo2 \
    fontconfig \
    fonts-liberation \
    fonts-noto-cjk \
    fonts-freefont-ttf \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i -E 's/^Components: main$/Components: main contrib/' /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && echo 'ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true' | debconf-set-selections \
    && apt-get install -y --no-install-recommends ttf-mscorefonts-installer \
    && fc-cache -f \
    && fc-match -f '%{family}\n' 'Times New Roman' | grep -qi 'Times New Roman' \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/scifigure
COPY requirements.txt ./
RUN pip install --no-cache-dir --index-url "${PIP_INDEX_URL}" -r requirements.txt
COPY renderer/fontconfig-local.conf /etc/fonts/conf.d/52-scifigure-font-alias.conf
RUN fc-cache -f \
    && fc-match -f '%{family}\n' 'Times New Roman' | grep -qi 'Times New Roman'
COPY renderer ./renderer

RUN useradd --system --uid 65532 --home-dir /tmp --shell /usr/sbin/nologin renderer
USER 65532:65532
