import { describe, expect, it } from 'vitest';
import * as XLSX from 'xlsx';
import {
  CLIENT_DATA_FILE_MAX_BYTES,
  inspectClientXlsxArchive,
  parseClientTabularPreview,
  validateClientDataFileSelection,
} from './clientTabularPreview';

function minimalZip(entries: Array<{ name: string; compressedSize?: number; uncompressedSize?: number }>): Buffer {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let localOffset = 0;
  for (const entry of entries) {
    const name = Buffer.from(entry.name, 'utf8');
    const compressedSize = entry.compressedSize ?? 0;
    const uncompressedSize = entry.uncompressedSize ?? compressedSize;
    const method = compressedSize === uncompressedSize ? 0 : 8;
    const local = Buffer.alloc(30 + name.length + compressedSize);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(method, 8);
    local.writeUInt32LE(compressedSize, 18);
    local.writeUInt32LE(uncompressedSize, 22);
    local.writeUInt16LE(name.length, 26);
    name.copy(local, 30);
    localParts.push(local);

    const central = Buffer.alloc(46 + name.length);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(method, 10);
    central.writeUInt32LE(compressedSize, 20);
    central.writeUInt32LE(uncompressedSize, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt32LE(localOffset, 42);
    name.copy(central, 46);
    centralParts.push(central);
    localOffset += local.length;
  }
  const centralDirectory = Buffer.concat(centralParts);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(entries.length, 8);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(centralDirectory.length, 12);
  eocd.writeUInt32LE(localOffset, 16);
  return Buffer.concat([...localParts, centralDirectory, eocd]);
}

function arrayBuffer(buffer: Buffer): ArrayBuffer {
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer;
}

function workbook(extra: Array<{ name: string; compressedSize?: number; uncompressedSize?: number }> = []): ArrayBuffer {
  return arrayBuffer(minimalZip([
    { name: '[Content_Types].xml' },
    { name: 'xl/workbook.xml' },
    ...extra,
  ]));
}

describe('client tabular preview boundary', () => {
  it('normalizes extensions and enforces the public single-file ceiling', () => {
    expect(validateClientDataFileSelection({ name: 'DATA.XLSX', size: 1024 } as File)).toBe('.xlsx');
    expect(() => validateClientDataFileSelection({ name: 'payload.exe', size: 10 } as File)).toThrow('仅支持');
    expect(() => validateClientDataFileSelection({ name: 'empty.csv', size: 0 } as File)).toThrow('空文件');
    expect(() => validateClientDataFileSelection({ name: 'large.csv', size: CLIENT_DATA_FILE_MAX_BYTES + 1 } as File)).toThrow('50 MB');
  });

  it('accepts the required XLSX container entries and rejects unsafe archive structure', () => {
    expect(inspectClientXlsxArchive(workbook())).toEqual({});
    expect(() => inspectClientXlsxArchive(workbook([{ name: '../escape.xml' }]))).toThrow('内部路径');
    expect(() => inspectClientXlsxArchive(workbook([
      { name: 'xl/worksheets/sheet1.xml', compressedSize: 1, uncompressedSize: 1_000_000 },
    ]))).toThrow('压缩比');

    const malformedLocalHeader = minimalZip([
      { name: '[Content_Types].xml' },
      { name: 'xl/workbook.xml' },
    ]);
    malformedLocalHeader.writeUInt16LE(99, 8);
    expect(() => inspectClientXlsxArchive(arrayBuffer(malformedLocalHeader))).toThrow('本地文件头与中央目录不一致');
  });

  it('defers valid workbooks that exceed the browser expansion budget', () => {
    const inspection = inspectClientXlsxArchive(workbook([
      { name: 'xl/worksheets/sheet1.xml', compressedSize: 1_000_000, uncompressedSize: 40 * 1024 * 1024 },
      { name: 'xl/sharedStrings.xml', compressedSize: 1_000_000, uncompressedSize: 30 * 1024 * 1024 },
    ]));
    expect(inspection.previewDeferredReason).toContain('服务端隔离解析');
  });

  it('accepts a normal workbook generated by the supported SheetJS runtime', () => {
    const generated = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(generated, XLSX.utils.aoa_to_sheet([
      ['sample', 'value'],
      ['A', 1],
      ['B', 2],
    ]), 'Measurements');
    const buffer = XLSX.write(generated, { type: 'buffer', bookType: 'xlsx', compression: true });

    expect(inspectClientXlsxArchive(arrayBuffer(buffer))).toEqual({});
  });

  it('always defers legacy BIFF workbooks to server isolation', async () => {
    const signature = new Uint8Array([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1, 0x00]);
    const file = new File([signature], 'legacy.xls', { type: 'application/vnd.ms-excel' });
    const preview = await parseClientTabularPreview(file);

    expect(preview.headers).toEqual([]);
    expect(preview.sampleRows).toEqual([]);
    expect(preview.previewDeferredReason).toContain('服务端隔离解析');
  });

});
